### ISSUE TITLE
Addiion of ATMEGA324PB core?

### ISSUE THREAD

**Issue by chrismcdaid1** [MCUdude/MightyCore#92]
Hi, Just wondering if you have any plans of adding the 324PB variant to the MightyCore.

**Comment by MCUdude** [comment]
Hi! I don't have plans adding support for it in the near future, but it shouldn't be too hard. Problem is, I don't have any hardware to test on, and new hardware needs to be fully tested before I can merge it into the master branch.

**Comment by MCUdude** [comment]
I've just pushed some [pre-compiled bootloader hex files for ATmega324PB](https://github.com/MCUdude/optiboot_flash/tree/master/atmega324pb) if you'd like to test it.

**Comment by chrismcdaid1** [comment]
Cheers,

I have hardware coming this week to test it on.

Regards,
Christopher McDaid
Research Engineer

[wisarlyit2]
T:  +353 (0)74 918 6460
E:  christopher.mcdaid@lyit.ie<mailto:christopher.mcdaid@lyit.ie>

**Comment by chrismcdaid1** [comment]
Thats Brilliant MCUdude. I look forward to testing it out. Many thanks.

**Comment by Luckysin13** [comment]
Readme still shows ATmega324PB as unsupported on master page.

Thanks for your hard work MCUdude, really appreciate it.

https://github.com/MCUdude/MightyCore#supported-microcontrollers

**Comment by MCUdude** [comment]
I'm still working on it. I'll merge it into master when it's ready. Not much work left though
